Ibcswap
sidefoundation/sidechain pull request #6
Opened 2023-03-13 21:41 UTC by DedicatedDev

- migrate chain with ibc-go v6
- Integrate ibcswap module

2023-03-13 23:48 UTC, liangping commented on Makefile
> +IBC_GO_URL          = https://raw.githubusercontent.com/cosmos/ibc-go/v6.0.0-beta1
Does it possible to use release version, we use `beta` version because only beta version has e2e test code. now we could keep e2e and upgrade to v6.0.0 release

2023-03-13 23:49 UTC, liangping commented on go.mod
> +	github.com/cosmos/ibc-go/v6 v6.1.0
here, we have v6.1.0. would be great to keep same

2023-03-13 23:51 UTC, liangping requested changes
a little suggestion

2023-03-14 01:47 UTC, DedicatedDev commented on Makefile
> +IBC_GO_URL          = https://raw.githubusercontent.com/cosmos/ibc-go/v6.0.0-beta1
please check new commit

2023-03-14 02:37 UTC, liangping approved these changes

2023-03-14 02:37 UTC, merged